dist: xenial
os:
- linux

language: node_js
node_js:
  - 15

addons:
  chrome: stable

cache:
  directories:
    - ./node_modules

install:
  - npm install

jobs:
  include:
    - stage: Lint
      script: npm run lint
    - stage: Unittests
      script: npm run test -- --watch=false --no-progress --browsers=ChromeHeadlessNoSandbox
    - stage: e2e tests
      script: npm run e2e
